apiVersion: apps/v1
kind: Deployment
metadata:
  name: content
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content
  template:
    metadata:
      labels:
        app: content
    spec:
      containers:
        - name: content
          image: docker.io/broga/content-app:{{ .Values.env.APP_VERSION }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: image-storage
              mountPath: /app/images
          resources:
            requests:
              cpu: '250m'
              memory: '100Mi'
            limits:
              cpu: '500m'
              memory: '200Mi'
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: shared-storage-claim
